book_type: short
chapter_titles: false
file_stub: Lorem
image_filename: pexels-ann-zzz-8452844.jpg
outfile_directory: example\
project_directory: example\
title: Lorem Ipsum
title_keyword: Lorem
word_count: 1,000
